# Generated by Django 5.2.7 on 2026-01-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='image_url2',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='land',
            name='image_url3',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
