# Generated by Django 5.2.7 on 2026-01-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_app', '0002_land_image_url2_land_image_url3'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='land',
            name='image_url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='land',
            name='image_url2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='land',
            name='image_url3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='land',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='land',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='land',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
