# Generated by Django 5.2.7 on 2026-01-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_app', '0003_land_is_approved_alter_land_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
