# Generated by Django 5.2.7 on 2026-01-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_app', '0004_alter_land_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
