# Generated by Django 5.2.7 on 2026-02-13 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_app', '0005_alter_land_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='land',
            name='image_url2',
        ),
        migrations.RemoveField(
            model_name='land',
            name='image_url3',
        ),
        migrations.AddField(
            model_name='land',
            name='description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='land',
            name='image2_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='land',
            name='image3_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='land',
            name='owner_phone',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='land',
            name='image_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='land',
            name='price',
            field=models.FloatField(),
        ),
    ]
