# Generated by Django 5.2.7 on 2026-02-13 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_app', '0006_remove_land_image_url2_remove_land_image_url3_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='land',
            old_name='image_url',
            new_name='image1',
        ),
        migrations.RenameField(
            model_name='land',
            old_name='image2_url',
            new_name='image2',
        ),
        migrations.RenameField(
            model_name='land',
            old_name='image3_url',
            new_name='image3',
        ),
        migrations.RemoveField(
            model_name='land',
            name='description',
        ),
        migrations.RemoveField(
            model_name='land',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='land',
            name='owner_phone',
        ),
        migrations.AddField(
            model_name='land',
            name='image4',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='land',
            name='image5',
            field=models.URLField(blank=True, null=True),
        ),
    ]
