# Generated by Django 5.2.7 on 2026-02-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_app', '0007_rename_image_url_land_image1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='land',
            name='owner_name',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='land',
            name='owner_phone',
            field=models.CharField(default='unknown', max_length=15),
            preserve_default=False,
        ),
    ]
