# Generated by Django 5.2.7 on 2026-02-13 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_app', '0008_land_description_land_owner_name_land_owner_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='land',
            name='latitude',
            field=models.FloatField(blank=True, default=10.787, null=True),
        ),
        migrations.AlterField(
            model_name='land',
            name='longitude',
            field=models.FloatField(blank=True, default=78.7047, null=True),
        ),
        migrations.AlterField(
            model_name='land',
            name='owner_name',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='land',
            name='owner_phone',
            field=models.CharField(default='unknown', max_length=15),
        ),
    ]
