# Generated by Django 5.2.7 on 2026-02-20 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_app', '0009_alter_land_description_alter_land_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='land',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='land',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='land',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='land',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='land',
            name='image5',
        ),
        migrations.AddField(
            model_name='land',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='land_images/'),
            preserve_default=False,
        ),
    ]
