# Generated by Django 5.2.7 on 2026-02-20 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_app', '0010_remove_land_image1_remove_land_image2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='land',
            name='image',
        ),
        migrations.AddField(
            model_name='land',
            name='image1',
            field=models.ImageField(default='none', upload_to='lands/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='land',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='lands/'),
        ),
        migrations.AddField(
            model_name='land',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='lands/'),
        ),
        migrations.AddField(
            model_name='land',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='lands/'),
        ),
        migrations.AddField(
            model_name='land',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='lands/'),
        ),
    ]
