# Generated by Django 5.2.7 on 2026-02-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_app', '0011_remove_land_image_land_image1_land_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='lands/'),
        ),
    ]
