# Generated by Django 5.2.7 on 2026-02-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_app', '0012_alter_land_image1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='owner_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='land',
            name='owner_phone',
            field=models.CharField(default='Unknown', max_length=15),
        ),
    ]
